#!/bin/sh
echo "### Running make clean..."
make clean
make dist-clean
echo "### Running aclocal..."
aclocal
echo "### Running autoconf..."
autoconf
echo "### Running automake..."
automake -a
echo "### Running ./configure..."
./configure
echo "### Running make..."
make
echo "### Running make check..."
make check
